modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dimension_adventure"
version="1.0.0"
displayName="Dimension adventure"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Пользователь, MCreator"

[[dependencies.dimension_adventure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




